remote_theme: pages-themes/slate@v0.2.0
layout: default
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

domain: musios.app
url: "https://musios.app"
baseurl: "/"

name: musios.app
title: musios.app
description: tools, scripts and docs for music nerds

exclude: [CNAME]
