name: musios.app
title: musios.app
tab_title: "musios.app: tools, scripts and docs for music nerds"
description: tools, scripts and docs for music nerds

domain: musios.app
url: "https://musios.app"
baseurl: "/"

exclude: [CNAME]

# Build settings
markdown: kramdown
theme: minima
