remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme


domain: musios.app
url: "https://musios.app"
baseurl: "/"

name: musios.app
title: musios.app
description: tools, scripts and docs for music nerds

exclude: [CNAME]
